services:
  api:
    build: .
    container_name: job-board-api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - job-board-network
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=jobboard

  mysql:
    image: mysql:8.0
    container_name: job-board-mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - job-board-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jobboard
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

networks:
  job-board-network:
    driver: bridge

volumes:
  mysql-data: